
replicaCount: 1

image:
  repository: skills-api
  pullPolicy: IfNotPresent
  tag: dev

namespace: default

service:
  type: NodePort
  port: 8080
  nodePort: 30354
  protocol: TCP
  targetPort: 8080
  portName: http

secrets:
  name: skills-api-secrets
  secretFilePath: "../../../skills_api/.env"
  type: Opaque

rolloutStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

postgres:
  database: J3NraWxscy1kZXYn
  password: password
  port: JzU0MzIn
  server: J3NraWxscy1hcGktZGV2LmNpb3RtcXhuZHU0dy5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20n
  user: root

resources: {}
resourceLimits: 
  cpu: "2"
  memory: "3Gi"
  requests:
    cpu: 1
    memory: "512Mi"

envFilePath: "../../../skills_api/.env"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
