apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skills-api.fullname" . }}
  labels:
    {{- include "skills-api.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "skills-api.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rolloutStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rolloutStrategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.rolloutStrategy.type }}
  template:
    metadata:
      labels:
        {{- include "skills-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
