apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "skills-api.labels" . | nindent 4 }}
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secrets.type }}
data:
  pg_skills_database: {{ .Values.postgres.database }}
  pg_skills_password: {{ .Values.postgres.password | b64enc}}
  pg_skills_port: {{ .Values.postgres.port }}
  pg_skills_server: {{ .Values.postgres.server }}
  pg_skills_user: {{ .Values.postgres.user | b64enc }}

