apiVersion: v1
kind: Service
metadata:
  name: {{ include "skills-api.fullname" . }}
  labels:
    {{- include "skills-api.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "skills-api.selectorLabels" . | nindent 4 }}
