apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skills-api
  name: skills-api
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skills-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skills-api
    spec:
      containers:
      - image: skills-api:dev
        imagePullPolicy: IfNotPresent
        name: skills-api
        envFrom:
          - secretRef:
              name: skills-api-secrets
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
