apiVersion: v1
kind: Service
metadata:
  labels:
    app: skills-api
  name: skills-api
  namespace: default
  
spec:
  ports:
  - nodePort: 30354
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: skills-api
  sessionAffinity: None
  type: NodePort

status:
  loadBalancer: {}
