# Generated by Django 3.2.10 on 2023-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('years_experience', models.SmallIntegerField()),
            ],
        ),
    ]
