# Generated by Django 3.2.10 on 2023-02-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('years_experience', models.SmallIntegerField()),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skills')),
            ],
        ),
    ]
